openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/KAKSIZOV/vfdsdfv/1.0.0
info:
  version: "1.0.0"
  title: fast-deposit
  description: Сервис осуществляет поиск последнего удачного депозита у 
               пользователя в разрезе платёжной системы для предзаполнения 
               платёжных реквизитов на frontend.
paths:
  /requisites:
     post:
      summary: Методы для поиска последнего удачного депозита у пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userID:
                  type: integer
                  description: Идентификатор пользователя
                  example: 123
              required:
                - userID
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
             schema:
               $ref: "#/components/schemas/200"
        '400':
          description: Отсутствует userId
          content:
            application/json:
             schema:
               $ref: "#/components/schemas/400"
       

components:
  schemas:
     200:
      type: object
      required:
        - status
        - data
      properties:
        status:
          type: integer
          example: 123
        data:
          type: array
          items:
            $ref: "#/components/schemas/200/data"
      data:
       type: object
       required:
        - payment_system
        - wallet
        - amount
       properties:
         payment_system:
           type: string
           example: "online-indonesian-banks"
         wallet:
           $ref: "#/components/schemas/200/wallet"
         amount:
           type: integer
           example: 300
      wallet:
       type: object
       required:
        - bankName
       properties:
         bankName:
           type: string
           example: "Maybank Indonesia(Virtual account)"   
           
     400:
       type: object
       required:
         - data
       properties:
         data:
           type: object
           required:
             - errors
           properties:
             errors:
               type: array
               items:
                 type: object
                 properties:
                   code:
                     type: integer
                     example: 400
                   message:
                     type: string
                     example: "Access denied."
